name: Build and Publish Plugin

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  generate-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'  # Adjust to your required Node.js version

      - name: Install dependencies and generate assets
        run: |
          sudo apt-get update
          sudo apt-get install -y make  # Install make utility if it's not available by default
          make init skip-composer  # Run your custom Makefile command

      - name: Print current directory and list assets
        run: |
          echo "Current directory: $(pwd)"
          echo "Contents of the repository:"
          ls -l assets/
          echo "Contents of assets/dist folder:"
          ls -lR assets/dist/

  commit-changes:
    runs-on: ubuntu-latest
    needs: generate-assets  # This job depends on the generate-assets job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit dist folder
        run: |
          # Ensure that dist/ folder exists after build

          echo "Current directory: $(pwd)"
          ls -l assets/
          
          if [ -d "assets/dist" ]; then
            git config --global user.name "puyaalexxx"
            git config --global user.email "puyaalexxx@gmail.com"
            git add -f assets/dist  # Force add the dist folder even if it's ignored in .gitignore
            git commit -m "Add dist folder for release" || echo "No changes to commit"
            git push origin HEAD:main  # Push the changes back to the main branch
          else
            echo "assets/dist/ folder not found after build, skipping commit."
            exit 1  # Exit with error code to fail the job
          fi

  create-packagist-release:
    runs-on: ubuntu-latest
    needs: commit-changes  # This job depends on the commit-changes job
    steps:
      - name: Create release on Packagist
        run: |
          curl -u "${{ secrets.PACKAGIST_TOKEN }}" -X POST -d '{"repository": "https://github.com/puyaalexxx/devhunters-fw"}' https://packagist.org/api/submit
        env:
          PACKAGIST_TOKEN: ${{ secrets.PACKAGIST_TOKEN }}  # Access the secret from GitHub
